### ISSUE TITLE
Release v0.1.0 inih files not included in zip

### ISSUE THREAD

**Issue by TzZek** [jerwuqu/notificue#3]
The files inside inih to be able to compile the program were not included in the .zip , easy work around is just to download and extract them from the repo, however I don't think this was intended?

**Comment by jerwuqu** [comment]
Those zips are automatically generated by GitHub and don't include git submodules. For later releases I could manually add the source archives, but for now you can run `git clone --recursive https://github.com/jerwuqu/notificue.git` and go from there. 

If/when later commits are made you should checkout the specific release version using `git checkout v0.1.0`.

Thanks for showing interest in the project!

**Comment by TzZek** [comment]
Oh my bad, wasn't aware of that just wanted something exactly like this as windows 10 notifications are terrible. Thanks for the information!
